# Generated by Django 3.0.4 on 2020-03-08 21:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('name', models.CharField(max_length=254)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('cover_art', models.FilePathField(max_length=254, path='/podcast-rss/podcast-images', recursive=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('media', models.FilePathField(max_length=254, path='/podcast-rss/podcast-episodes', recursive=True)),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.Podcast')),
            ],
        ),
    ]
