# Generated by Django 3.2.7 on 2021-09-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='cover_art',
            field=models.FilePathField(max_length=254, path='/data/podcast-assets/images', recursive=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='media',
            field=models.FilePathField(max_length=254, path='/data/podcast-assets/episodes', recursive=True),
        ),
    ]
